version: '3.1'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu

    command: sleep infinity
    restart: always
    ports:
      - 8889:8889

    volumes:
      - ../..:/workspaces:cached
